### ISSUE TITLE
wsl_params.ps and CreateTask.ps1 are the same.

### ISSUE THREAD

**Issue by Oyami-Srk** [SadarSSI/WSLStartService#1]
I think it may be mistakely commited at d9cfe0d496a3e3901712802fcc36fea59951e802.

**Comment by SadarSSI** [comment]
Hello,
Sorry I'm not very comfortable with GitHub I hadn't seen your request.

I completely redeveloped these scripts in a new repository https://github.com/SadarSSI/WSL-WatchDog with a yaml configuration file

I propose a solution to work around the WSL regression / bug mentioned here https://github.com/microsoft/WSL/issues/8161
